version: 2

# taken from https://browniebroke.com/blog/specify-docs-dependency-groups-with-poetry-and-read-the-docs/
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      - pip uninstall -y sphinx
      # Install dependencies
      - poetry install --with dev

sphinx:
  configuration: docs/conf.py
