version: 2

# use uv to export dependency groups for Read the Docs installs
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - pip uninstall -y sphinx
      - uv export --frozen --all-extras --group dev --no-hashes --no-emit-project -o requirements.txt
      - pip install -U -r requirements.txt

sphinx:
  configuration: docs/conf.py
